### ISSUE TITLE
A little hint for anyone not willing to go this far

### ISSUE THREAD

**Issue by pannal** [ucrawler/nntplexer#1]
Sorry for highjacking this repository's issue area.

If this seems too much for you guys just to share your accounts, have a look at [socat](http://www.dest-unreach.org/socat/) (not affiliated in any way), especially at the TCP forwarders. Achieves the "same" with basically zero compute cost, storage, caching, or other software setup, including secure nntp.

**Comment by ucrawler** [comment]
Thanks for your feedback. I’m closing this as it’s not an issue.
